### PR TITLE
Add timers for each sweep

### PR DESCRIPTION
**Pull request by douglasjacobsen**
This merge adds timers for each of the individual sweep directions.
It helps users determine performance from each of the sweeps.

### CODE REVIEW

**Comment by douglasjacobsen** [comment]
For more of a discussion on this, please see: https://github.com/UK-MAC/mega-stream/pull/4#issuecomment-356014266 and https://github.com/UK-MAC/mega-stream/pull/4#issuecomment-356087375

**Comment by tomdeakin** [comment]
In principal this is interesting information to report, but it would need to appear in both the 2D and 3D versions.

Also, the currently submitted change adds a lot of unnecessary `MPI_Wtime` calls around the MPI communication. Each MPI send/recv is actually timed once inside the comms module and also in the kernel itself. Really the timing should be redesigned to prevent timing the same thing twice.

It would be important to ensure that any additional MPI calls inside the main compute kernel do not add any overhead or change the performance profile of the kernel. Do you have a feeling for the overhead of the timers in the kernel?

**Comment by douglasjacobsen** [comment]
@tomdeakin In my tests, the overhead is negligible currently, but you can see https://github.com/UK-MAC/mega-stream/pull/4#issuecomment-356087375 for more detailed comparisons.

I'd agree with your comment though. For the purposes I was trying to time, the timers inside the comms module were not sufficient. I wanted to get a good feeling for how much time was spent doing the communication, including instructions that were necessary to prepare for the communication.

I haven't spent any time looking at the 2D sweep version. I can look at it, but it likely will be a long time before I get around to it.

**Comment by tomdeakin** [comment]
I think based on your commit, the interesting timings that would be good to output are:
- time in the MPI calls
- time in (logical) communications (this is what your commit aims to time, so that the buffer copies, etc. are included)
- total time in each sweep direction

This means we'll keep the double `MPI_Wtime` calls, but I think that's fine as your comment shows it makes little difference to total runtime.

It's important that the 2D and 3D versions maintain consistent, so any changes to one will need to be ported to the other.

I'll work on capturing these timings and submit a version for you to check over.

**Pull request closed without merging**
